# Generated by Django 4.2.4 on 2023-08-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='pdf',
            field=models.FileField(null=True, upload_to='pdfs'),
        ),
    ]
